### ISSUE TITLE
[project] - Pull-Request

### ISSUE THREAD

**Issue by BuffePOK** [logistics-ecosystem/order-management#8]

**Comment by BuffePOK** [comment]
Oops, we might have jumped the gun and started coding before creating a microservice skeleton. Now we have an exciting quest to merge our masterpieces! 😅 But no worries, @OPapHub , my trusty companion, is already coming to the rescue! 💪 Thanks for your understanding and willingness to help us sort this out! 🙏

**Comment by ghost** [comment]
Completed a pull request, fixed merging issues and cleaned code!
[Commit details](https://github.com/logistics-ecosystem/order-management/commit/bbf15c209751062932d3a7a9333c50027ffd5283)
